import math
from random import randint
import turtle
mick = turtle.clone()
mick.setposition(20,0)
mick.shape("circle")
mick.color("black", "royalblue")
mick.shapesize(1, 2, 3)
mick.shapesize(outline=3)
john = mick.clone()
john.shapesize(1, 2, 3)
john.shapesize(outline=3)
john.setposition(20,40)
john.color("black", "lime")
Yvonne = john.clone()
Yvonne.setposition(20,80)
Yvonne.shapesize(1, 2, 3)
Yvonne.shapesize(outline=3)
Yvonne.color("black", "magenta")
Alice = Yvonne.clone()
Alice.setposition(20,120)
Alice.shapesize(1, 2, 3)
Alice.shapesize(outline=3)
Alice.color("black", "gold")
#Race time
turtle.delay(100)
mick.speed(randint(1,10))
mick.forward(100)
mick.speed(randint(1,10))
mick.forward(100)
john.speed(randint(1,10))
john.forward(100)
john.speed(randint(1,10))
john.forward(100)
Yvonne.speed(randint(1,10))
Yvonne.forward(100)
Yvonne.speed(randint(1,10))
Yvonne.forward(100)
Alice.speed(randint(1,10))
Alice.forward(100)
Alice.speed(randint(1,10))
Alice.forward(100)
turtle.hideturtle

